version: "3.9"

services:
  mongo_db:
    container_name: mongo_container
    image: tejdocker32/restaurantmongo:latest

  backend:
    image: tejdocker32/backend-img
    ports:
      - "4000:4000"
    environment:
      - DBURL=mongodb://mongo_db:27017/restaurantsDB
      - PORT=4000
  frontend:
    image: tejdocker32/frontend-img
    ports:
      - "3000:3000"
