version: '3.9'

services:
  mongo_db:
    container_name: mongo_container
    image: restaurantmongo:latest

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      - DBURL=mongodb://mongo_db:27017/restaurantsDB
      - PORT=4000
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    