---
- name: Deploy MERN Application
  hosts: all

  vars:
    ansible_python_interpreter: /Users/varadbadhe/opt/anaconda3/share/man/man1/python3.1
  tasks:
    - name: Pull Frontend Image
      docker_image:
        name: jaguar14/frontend-img:latest
        source: pull

    - name: Pull Backend Image
      docker_image:
        name: jaguar14/backend-img:latest
        source: pull

    - name: Run Docker Compose
      command: docker compose up
