---
- name: Deploy MERN Application
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Frontend Image
      docker_image:
        name: jaguar14/frontend-img:latest
        source: pull

    - name: Pull Backend Image
      docker_image:
        name: jaguar14/backend-img:latest
        source: pull

    - name: Run Docker Compose
      command: docker compose up
